update

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,35 +1,41 @@
 #!/usr/bin/env bash
-# Displays informtation about subdomains.
+# Displays information about subdomains.
 
-# uncomment for debugging purposes.
-#set -x
+# Uncomment for debugging purposes.
+# set -x
 
-# for the checker to work please remove the colors.
-
-# colors
+# Colors
 blue='\e[1;34m'
 brown='\e[0;33m'
 reset='\033[0m'
 
-# variables & parameters
+# Variables
 subdomains=( "www" "lb-01" "web-01" "web-02" )
 domain="$1"
 sub="$2"
 
+# Function to display information for a given subdomain
 dig_cmd () {
-	# func variables
-	sub="$2"
-	INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
-	IP=$(echo "$INFO" | awk '{print $5}')
-	RECORD=$(echo "$INFO" | awk '{print $4}')
+    local sub="$2"
+    local INFO=$(dig "$sub.$domain" +short)
 
-	echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
+    if [ -n "$INFO" ]; then
+        local IP=$(echo "$INFO" | awk 'NR==1')
+        local RECORD=$(echo "$INFO" | awk 'NR==2')
+        echo -e "${brown}The subdomain ${blue}$sub${brown} is a ${blue}$RECORD${brown} record and points to ${blue}$IP${reset}"
+    else
+        echo -e "${brown}Unable to resolve subdomain ${blue}$sub${reset}"
+    fi
 }
 
+# Main
 if [ $# -eq 1 ]; then
-	for subs in "${subdomains[@]}"; do
-		dig_cmd "$domain" "$subs"
-	done
+    for subs in "${subdomains[@]}"; do
+        dig_cmd "$domain" "$subs"
+    done
 elif [ $# -eq 2 ]; then
-	dig_cmd "$domain" "$sub"
+    dig_cmd "$domain" "$sub"
+else
+    echo "Usage: $0 <domain> [subdomain]"
+    exit 1
 fi
